packages:
  - 'apps/*'
  - 'tooling/*'
  - 'packages/*'

catalog:
  # TRPC & React Query
  "@trpc/client": ^11.0.0-rc.828
  "@trpc/server": ^11.0.0-rc.828
  "@trpc/tanstack-react-query": ^11.0.0-rc.828
  "@tanstack/react-query": ^5.67.3

  # Misc
  "better-auth": ^1.2.4
  "zod": ^3.24.2
  "tailwindcss": ^4.0.14

  # Linting
  "eslint": ^9.19.0

  # Formatting
  "prettier": ^3.5.1
  "prettier-plugin-tailwindcss": ^0.6.11
  "prettier-plugin-classnames": ^0.7.7
  "prettier-plugin-merge": ^0.7.2
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1

  # Typescript
  "typescript": ^5.7.3

catalogs:
  react18:
    "react": 18.3.1
    "react-dom": 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    "react": ^19.0.0
    "react-dom": ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
