/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AWS_BEDROCK_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_BEDROCK_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AcmeAPI": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AcmeDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "AcmeFrontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AcmeResumeBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AcmeVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DEEPSEEK_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}